import ProjectDescription

let workspace = Workspace(
    name: "Scrumdinger",
    projects: [
        "Projects/**"
    ],
    generationOptions: .options(autogeneratedWorkspaceSchemes: .disabled)
)
